### ISSUE TITLE
Add Adam optimizer

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartlearner#48]
We could start from either: 
https://github.com/mgermain/MADE/blob/master/MADE/update_rules.py#L121
and
https://github.com/mgermain/MADE/blob/master/MADE/update_rules.py#L159

I don't remember the difference between the two. @mgermain can you enlight us?

PS: Sometime ago (before we refactored everything), I'd made a version of it: https://github.com/MarcCote/smartlearner/blob/basic_structure/smartpy/update_rules/adam.py

**Comment by ASalvail** [comment]
Done in #51
