### ISSUE TITLE
Buffer size in task ClassificationError is hardcoded

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartlearner#5]
Find how to adjust buffer size dynamically. Will be probably useful for a lot of tasks.

**Comment by mgermain** [comment]
Buffer size in task ?

**Comment by MarcCote** [comment]
Sometimes a Task/View needs to loop through the dataset. However, with big model/dataset it is not possible to parse the whole dataset at once, so it would require some kind of batch processing.

**Comment by MarcCote** [comment]
These kind of tasks should take a `batch_size` in argument.
