### ISSUE TITLE
Should StoppingCriterion be a Task?

### ISSUE THREAD

**Issue by MarcCote** [SMART-Lab/smartlearner#6]
Check if `StoppingCriterion` should subclass `Task` or not.

**Comment by mgermain** [comment]
Any pros or cons ?

**Comment by MarcCote** [comment]
Right now, I don't see any cases that would require `StoppingCriterion` subclassing `Task`. Worst case scenario, if really needed, a stopping criterion could subclass both `StoppingCriterion` and `Task.

**Comment by MarcCote** [comment]
Stopping criteria are now considered as tasks. However, they will be separated from normal tasks and put in another file `smartlearner.tasks.stopping_criteria`. The main particularity of a stopping criterion is it will raise a `TrainingExit` exception.

**Comment by MarcCote** [comment]
Closed by #26
