### ISSUE TITLE
Sampling is very slow

### ISSUE THREAD

**Issue by ASalvail** [SMART-Lab/smartlearner#66]
For some reason, adding noise to the gradient (feature introduce by #65 ) slows the training by about 100%, which is unacceptable when you understand this is just sampling numbers from a RNG.

This might be worth investigating.

**Comment by MarcCote** [comment]
Try using `from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams` instead. It supports GPU.

**Comment by ASalvail** [comment]
That did the work. Thx!

**Comment by MarcCote** [comment]
I'll change the line in PR #62.
